# Generated by Django 6.0.1 on 2026-03-18 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0005_post_author"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="featured_image",
            field=models.URLField(blank=True, default=""),
        ),
    ]
